### ISSUE TITLE
Client-Admin - Jumpmachine

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/kubernetes-vagrant#5]
### client-admin VM

Rename Server
mssql-jump => client-admin 
IP Address => 172.17.8.201

  - [x] - 1  - VM Provision Error

![capture](https://user-images.githubusercontent.com/887805/41950642-f2f7e226-7994-11e8-92ee-4612032c7713.PNG)

- [x] - 2  - Save Kube Config  to local disk

https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_config/

``` /vagrant/tokens``` (Host Machine Filesystem)

![untitled](https://user-images.githubusercontent.com/887805/41950076-6d0e5f84-7992-11e8-8f78-4dc53e72c1dc.png)

- [x] - 3  - Configure kubectl with kubeconfig

 kubectl  - Point to Cluster master node (Get Configuration from local file system token

- [x] - 4  - Configure Install Helm Client

Helm Chart Should deploy helm charts to the Cluster on this machine

**Comment by dmitryint** [comment]
@stuartshay 
>2 - Save Kube Dashboard Token to local disk
it seems to me that this does not make sense since the token has a default lifetime of 15 minutes.

**Comment by stuartshay** [comment]
I think kube config will create valid cert
https://kubernetes-v1-4.github.io/docs/user-guide/kubectl/kubectl_config/

**Comment by stuartshay** [comment]
This Great !!!, 
Would like to do all deployments of Helm Charts form the Client  
(Running Helm from Ansible might not be the best way)
