### ISSUE TITLE
K8 Cluster 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/kubernetes-vagrant#6]
SQL Server Ansible playbook - Error

- All Helm Chart Deployment Fail 
- Needed to Run  ``` sudo helm init``` on master

![capture](https://user-images.githubusercontent.com/887805/41939475-e9642868-7963-11e8-9649-7d971b384b8f.PNG)

```
TASK [kubernetes-apps/helm : Helm | Install MSSQL] *****************************
Wednesday 27 June 2018  03:45:31 +0000 (0:00:00.814)       0:25:53.146 ********
fatal: [k8s-01]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/helm", "init", "/usr/local/bin/helm", "repo", "add", "incubator", "https://kubernetes-charts-incubator.storage.googleapis.com", "/usr/local/bin/helm", "install", "--name", "mymssql", "stable/mssql-linux", "--set", "acceptEula.value=Y", "--set", "edition.value=Developer"], "delta": "0:00:00.174830", "end": "2018-06-27 03:45:31.973569", "msg": "non-zero return code", "rc": 1, "start": "2018-06-27 03:45:31.798739", "stderr": "Error: unknown flag: --name", "stderr_lines": ["Error: unknown flag: --name"], "stdout": "", "stdout_lines": []}
```

**Comment by xmavrck** [comment]
I have updated the ansible script added for installing MySQL server. 
also, have tested the same, we need to have a pause to make sure the helm tiller pod is ready so we can install the MySQL server. 

![selection_378](https://user-images.githubusercontent.com/13379289/41994859-741c7f00-7a6d-11e8-846f-d1e7a8bd48a3.png)

please check the updated scripts

**Comment by stuartshay** [comment]
SQL Server is installed but I don't think the Volumes is not setup

See this Issue
https://github.com/stuartshay/kubernetes-vagrant/issues/4

Go into Dashboard 

![capture](https://user-images.githubusercontent.com/887805/42014677-806cb6ae-7a71-11e8-8feb-fd628bae0651.PNG)

**Comment by xmavrck** [comment]
yes, volumes need to set up differently we have to pass our storage class, and sizes. will start the work on the issue no  4

**Comment by stuartshay** [comment]
Closing Issue - Will Create new issue
